bemanproject/optional

.github/workflows/ci.yml
docs/debug-ci.md
src/Beman/Optional26/CMakeLists.txt

Enable clang-19 testing on CI ( #1 )
It seems that the previous errors that we had with running clang-19 + Asan are connected to gtest. Check [gist](https://gist.github.com/neatudarius/87cbb37a1821e4dcbf773906fb15f8ae): 
```shell
#10 0x55f30b5bbd1e in __cxx_global_var_init /home/runner/work/Beman.Optional26/Beman.Optional26/src/Beman/Optional26/tests/optional.t.cpp:14:1
```
Literally here we just test gtest :( I also created an executable with a single file (outside the Beman.Optional26 tree) and got the same results.
Found the fix looking through some posts:
* https://github.com/llvm/llvm-project/issues/58404
* https://stackoverflow.com/questions/41552966/getting-new-delete-type-mismatch-from-asan

Enable clang-19 testing on CI

---

include/Beman/Optional26/optional.hpp

Following the suggestion in [_Don’t reopen `namespace std`_](https://quuxplusone.github.io/blog/2021/10/27/dont-reopen-namespace-std/).
The change also works around a bug of MSVC (reduced and [reported on DevCom](https://developercommunity.visualstudio.com/t/MSVC-doesnt-accept-specialization-defin/10732088)).
Godbolt links:
- Before: https://godbolt.org/z/1bf1458Pf
- After: https://godbolt.org/z/1eanosrob
Drive-by: Remove emoji `🔗` from the synopsis comments, which seems to be copied from https://eel.is/c++draft/optional.syn.

Avoid reopening namespace `std`

---

include/Beman/Optional26/optional.hpp
src/Beman/Optional26/tests/optional.t.cpp
src/beman/optional26/tests/optional.t.cpp

A std::hash implementation for optional, the hash of the underlying value, or 0 for disengaged.

Implement std::hash for beman::optional

---

.github/workflows/ci.yml
.github/workflows/pre-commit.yml
include/Beman/Optional26/optional.hpp
src/Beman/Optional26/tests/optional.t.cpp
src/Beman/Optional26/tests/optional_constexpr.t.cpp
src/Beman/Optional26/tests/optional_ref.t.cpp

There's a lot of commits in this PR — feel free to cherry-pick (but I think they all need to be taken/addressed, one way or another). The really important ones are:
```
commit 4448d97dbd98e017203931e4a9f9a5a8ddb831e8
Author: Arthur O'Dwyer <arthur.j.odwyer@gmail.com>
Date:   Mon Sep 16 13:06:42 2024 -0400
[test] Add a green test for overload resolution
commit 986b975ad718613351aa1fe4ce20d75e6f956c41
Author: Arthur O'Dwyer <arthur.j.odwyer@gmail.com>
Date:   Mon Sep 16 12:20:19 2024 -0400
Support optional<T&>::emplace, and add tests
The return type of `emplace` had been wrong; `emplace` returns a
reference to the emplaced value (in this case, the T& reference
that was bound), not `*this`.
The new tests are red before the patch and green afterward.
commit …
```

Fix some bugs in optional<T&>; add tests for them

---

CMakeLists.txt
Makefile
README.md
examples/CMakeLists.txt
include/beman/optional26/CMakeLists.txt
src/beman/optional26/CMakeLists.txt
src/beman/optional26/tests/CMakeLists.txt
src/beman/optional26/tests/test_constructor_fail.cpp

This changes the install and include  directory strategy to use FILE_SETs with type HEADERS. 
Moves the creation of the targets and named header file sets upward so they exist in order to add the files locally in the src and include directories. Change the installs to use components so we can install just the necessary headers and not the empty library. 
Also make the option to build headers named for the project so it doesn't affect other included projects.
Exclude google from all so it doesn't get installed for the "all" component. 
Remove the cmake export install, at least for now. It was not working correctly. It's probably not strictly necessary for vcpkg or conan integration.

Install sets

---

.github/workflows/ci.yml
CMakePresets.json
etc/clang-20-toolchain.cmake

Partial fix for #77 
- clang-20 full suport (local preset + CI)
- clang-16 partial support (only local preset support; llvm.sh fails to install clang-16 on CI).
More discussions will be done in https://github.com/beman-project/beman/issues/34.  This PR just allows us to tests on more setups.

Add more compiler support

---

CITATION.cff
README.md
src/beman/optional26/tests/test_constructor_fail.cpp

https://github.com/bemanproject/beman/issues/65

[optional26 repo] Update docs: org renamed to bemanproject

---

.github/workflows/ci.yml
README.md
cmake/gcovr.cfg.in

This commit provides support for Coveralls CI by leveraging the existing Gcov build configuration, adding configuration so that gcovr generates coverage data in Coveralls JSON format, and adding steps to the CI build job that are activated only if the matrix entry is configured for coverage, which generate coverage data and deliver it to Coveralls.
It also adds a coverage badge to the README.

Add support for Coveralls to CI

---

include/beman/optional26/optional.hpp
src/beman/optional26/tests/optional.t.cpp

Also, refactor some other places to make use of the 'construct' helper that handles the flag.
This adds some tests for the non-trivial assignment operators, for all six cases:
- copy/move from engaged to engaged
- copy/move from engaged to empty
- copy/move from empty to engaged

Set 'engaged' flag on assignment correctly

---

include/beman/optional26/optional.hpp
src/beman/optional26/tests/optional.t.cpp
src/beman/optional26/tests/test_types.hpp

This adds the missing operator and a test.

Add missing assignment operator from 'nullopt_t'

---

include/beman/optional26/optional.hpp
src/beman/optional26/tests/optional.t.cpp
src/beman/optional26/tests/test_types.hpp

Moving `optional<T&>` into `optional<T>` should probably not result in a move of the remote value. Because of reference collapsing, the constraints of the move constructor/assignment operator of `optional<T>` already check for a copy of the remote value, not a move.
This makes the code match the constraints by ~~moving the `move` before the dereference, since for `optional<T&>`, `*std::move(rhs)` always results in a lvalue reference, not a rvalue reference.~~ introducing new constructor/assignment overloads for `optional<T&>`.
edit: fixes #92
edit: updated for new approach

When moving a 'optional<T&>', don't move the remote value

---

include/beman/optional26/optional.hpp
src/beman/optional26/tests/optional.t.cpp

For `enable_forward_value`, I just reordered the constraints so that the check against `optional` comes first. This fixes a "satisfaction of constraint 'detail::enable_forward_value<T, U>' depends on itself" error on clang.
For `enable_from_other` I introduced a `!std::is_same_v<T, U>` as the first check. This also fixes a "satisfaction of constraint ... depends on itself" error. This check should lead to no change in behavior as in the case where `T` and `U` are the same, `optional<T>`'s copy/move constructors should be used anyway.

Modify constructor constraints to make 'optional<any>' work on libc++

---

include/beman/optional26/optional.hpp

The overloads date back to C++ versions that needed them to distinguish if `explicit` was conditional or not. As `explicit` now takes an expression, the additional overloads are entirely redundant.

Remove redundant overloads on is_convertible

---

README.md
examples/README.md

https://github.com/bemanproject/beman/issues/85
Run example:

Fix broken CE links in examples/

---

Makefile
examples/optional_ref.cpp
include/beman/optional/optional.hpp
papers/P2988/Makefile
papers/P2988/head-optional.tex
papers/P2988/new-optional.tex
papers/P2988/optional_ref_wording.tex
tests/beman/optional/optional_ref.t.cpp

Fixes underlying std::move problem
Changes a static_cast where there is a chance of undefined behavior. 
Paper as presented in Hagenberg.

Fixes to optional

---

.github/workflows/ci.yml
.markdownlint.yaml
.pre-commit-config.yaml
CMakeLists.txt
Makefile
README.md
cmake/use-fetch-content.cmake
lockfile.json
tests/beman/optional/CMakeLists.txt

Use the new find-package support from the exemplar project, add documentation, and make the failure to find the GTest package in the common case a little friendlier.

Find package

---

README.md

https://github.com/bemanproject/optional/issues/114

Add proper example for optional ref in root README

---

.github/workflows/ci.yml

Uses newly introduced testing container (https://github.com/bemanproject/infra/pull/11) to simplify CI.

Use generalized testing container

---

.github/workflows/.yamllint
.github/workflows/ci.yml

Apt update and upgrade as first step in CI.

Update ci configuration to update and upgrade packages

---

Makefile
etc/gcc-15-toolchain.cmake
etc/gcc-16-toolchain.cmake
etc/gcc-flags.cmake
include/beman/optional/optional.hpp
tests/beman/optional/optional_range_support.t.cpp

GCC 15 release branch and GCC 16 have support for format_kind, revealing that the support in beman.optional has always been broken.

Format kind

---

Makefile
etc/clang-20-toolchain.cmake
etc/clang-21-toolchain.cmake
etc/gcc-flags.cmake
tests/beman/optional/optional.t.cpp
tests/beman/optional/optional_constexpr.t.cpp
tests/beman/optional/optional_ref.t.cpp

Add more coverage. 
May make coverage percent go down as more functions are instantiated.

More coverage

---

etc/clang-flags.cmake
etc/gcc-flags.cmake
etc/gcc-toolchain.cmake
tests/beman/optional/optional_range_support.t.cpp

Make unit testing constexpr compatible in C++20. 
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=120868 was in the way, at least partially. 
Fixes #123

Constexpr 20

---

include/beman/optional/optional.hpp

Wrong docs were applied to `emplace`, and added details to  other functions.

Improve and repair some docs
